// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class QueueSnapshot {
  final List<String> paths;
  final int currentIndex;
  final BigInt positionMs;
  final bool shuffle;

  const QueueSnapshot({
    required this.paths,
    required this.currentIndex,
    required this.positionMs,
    required this.shuffle,
  });

  @override
  int get hashCode =>
      paths.hashCode ^
      currentIndex.hashCode ^
      positionMs.hashCode ^
      shuffle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueueSnapshot &&
          runtimeType == other.runtimeType &&
          paths == other.paths &&
          currentIndex == other.currentIndex &&
          positionMs == other.positionMs &&
          shuffle == other.shuffle;
}
