// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/catalog.dart';
import 'api/enrich.dart';
import 'api/queue.dart';
import 'api/settings.dart';
import 'api/simple.dart';
import 'api/tags.dart';
import 'catalog/scan.dart';
import 'catalog/schema.dart';
import 'dart:async';
import 'dart:convert';
import 'db.dart';
import 'enrich/progress.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tags.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1838217848;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_olivier',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCatalogAddRoot(
      {required String dbPath, required String path});

  Future<List<String>> crateApiCatalogAlbumFilePaths(
      {required String dbPath, required String releaseMbid});

  Future<void> crateApiEnrichClearMbCache({required String dbPath});

  Stream<EnrichProgress> crateApiEnrichEnrichLibrary(
      {required String dbPath, required bool force});

  Future<String?> crateApiTagsExtractCover(
      {required String filePath, required String cacheDir});

  Future<String?> crateApiSettingsGetSetting(
      {required String dbPath, required String key});

  Future<void> crateApiSimpleInitApp();

  Future<List<Album>> crateApiCatalogListAlbums(
      {required String dbPath, required String albumArtistMbid});

  Future<List<Artist>> crateApiCatalogListArtists(
      {required String dbPath, String? after, required int limit});

  Future<List<String>> crateApiCatalogListRoots({required String dbPath});

  Future<List<Track>> crateApiCatalogListTracks(
      {required String dbPath, required String releaseMbid});

  Future<QueueSnapshot?> crateApiQueueLoadQueue({required String dbPath});

  String crateApiSimpleOlivierVersion();

  Future<TrackTags> crateApiTagsReadTrackTags({required String path});

  Future<void> crateApiCatalogRecordPlay(
      {required String dbPath,
      required PlatformInt64 trackId,
      required PlatformInt64 playedAt});

  Future<void> crateApiCatalogRemoveRoot(
      {required String dbPath, required String path});

  Future<void> crateApiQueueSaveQueue(
      {required String dbPath, required QueueSnapshot snapshot});

  Stream<ScanProgress> crateApiCatalogScanLibrary(
      {required String dbPath, required List<String> roots});

  Future<void> crateApiSettingsSetSetting(
      {required String dbPath, required String key, required String value});

  Future<String?> crateApiCatalogTrackPath(
      {required String dbPath, required PlatformInt64 trackId});

  Future<List<String>> crateApiCatalogTrackPathsForArtist(
      {required String dbPath, required String albumArtistMbid});

  Future<List<QueueTrack>> crateApiCatalogTracksForPaths(
      {required String dbPath, required List<String> paths});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCatalogAddRoot(
      {required String dbPath, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogAddRootConstMeta,
      argValues: [dbPath, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogAddRootConstMeta => const TaskConstMeta(
        debugName: "add_root",
        argNames: ["dbPath", "path"],
      );

  @override
  Future<List<String>> crateApiCatalogAlbumFilePaths(
      {required String dbPath, required String releaseMbid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(releaseMbid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogAlbumFilePathsConstMeta,
      argValues: [dbPath, releaseMbid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogAlbumFilePathsConstMeta =>
      const TaskConstMeta(
        debugName: "album_file_paths",
        argNames: ["dbPath", "releaseMbid"],
      );

  @override
  Future<void> crateApiEnrichClearMbCache({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEnrichClearMbCacheConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEnrichClearMbCacheConstMeta => const TaskConstMeta(
        debugName: "clear_mb_cache",
        argNames: ["dbPath"],
      );

  @override
  Stream<EnrichProgress> crateApiEnrichEnrichLibrary(
      {required String dbPath, required bool force}) {
    final sink = RustStreamSink<EnrichProgress>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_bool(force, serializer);
        sse_encode_StreamSink_enrich_progress_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEnrichEnrichLibraryConstMeta,
      argValues: [dbPath, force, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEnrichEnrichLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "enrich_library",
        argNames: ["dbPath", "force", "sink"],
      );

  @override
  Future<String?> crateApiTagsExtractCover(
      {required String filePath, required String cacheDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        sse_encode_String(cacheDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTagsExtractCoverConstMeta,
      argValues: [filePath, cacheDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagsExtractCoverConstMeta => const TaskConstMeta(
        debugName: "extract_cover",
        argNames: ["filePath", "cacheDir"],
      );

  @override
  Future<String?> crateApiSettingsGetSetting(
      {required String dbPath, required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSettingsGetSettingConstMeta,
      argValues: [dbPath, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsGetSettingConstMeta => const TaskConstMeta(
        debugName: "get_setting",
        argNames: ["dbPath", "key"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<List<Album>> crateApiCatalogListAlbums(
      {required String dbPath, required String albumArtistMbid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(albumArtistMbid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_album,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogListAlbumsConstMeta,
      argValues: [dbPath, albumArtistMbid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogListAlbumsConstMeta => const TaskConstMeta(
        debugName: "list_albums",
        argNames: ["dbPath", "albumArtistMbid"],
      );

  @override
  Future<List<Artist>> crateApiCatalogListArtists(
      {required String dbPath, String? after, required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_opt_String(after, serializer);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_artist,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogListArtistsConstMeta,
      argValues: [dbPath, after, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogListArtistsConstMeta => const TaskConstMeta(
        debugName: "list_artists",
        argNames: ["dbPath", "after", "limit"],
      );

  @override
  Future<List<String>> crateApiCatalogListRoots({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogListRootsConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogListRootsConstMeta => const TaskConstMeta(
        debugName: "list_roots",
        argNames: ["dbPath"],
      );

  @override
  Future<List<Track>> crateApiCatalogListTracks(
      {required String dbPath, required String releaseMbid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(releaseMbid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_track,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogListTracksConstMeta,
      argValues: [dbPath, releaseMbid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogListTracksConstMeta => const TaskConstMeta(
        debugName: "list_tracks",
        argNames: ["dbPath", "releaseMbid"],
      );

  @override
  Future<QueueSnapshot?> crateApiQueueLoadQueue({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_queue_snapshot,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiQueueLoadQueueConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQueueLoadQueueConstMeta => const TaskConstMeta(
        debugName: "load_queue",
        argNames: ["dbPath"],
      );

  @override
  String crateApiSimpleOlivierVersion() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleOlivierVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleOlivierVersionConstMeta =>
      const TaskConstMeta(
        debugName: "olivier_version",
        argNames: [],
      );

  @override
  Future<TrackTags> crateApiTagsReadTrackTags({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_track_tags,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTagsReadTrackTagsConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagsReadTrackTagsConstMeta => const TaskConstMeta(
        debugName: "read_track_tags",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiCatalogRecordPlay(
      {required String dbPath,
      required PlatformInt64 trackId,
      required PlatformInt64 playedAt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_i_64(trackId, serializer);
        sse_encode_i_64(playedAt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogRecordPlayConstMeta,
      argValues: [dbPath, trackId, playedAt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogRecordPlayConstMeta => const TaskConstMeta(
        debugName: "record_play",
        argNames: ["dbPath", "trackId", "playedAt"],
      );

  @override
  Future<void> crateApiCatalogRemoveRoot(
      {required String dbPath, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogRemoveRootConstMeta,
      argValues: [dbPath, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogRemoveRootConstMeta => const TaskConstMeta(
        debugName: "remove_root",
        argNames: ["dbPath", "path"],
      );

  @override
  Future<void> crateApiQueueSaveQueue(
      {required String dbPath, required QueueSnapshot snapshot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_box_autoadd_queue_snapshot(snapshot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiQueueSaveQueueConstMeta,
      argValues: [dbPath, snapshot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQueueSaveQueueConstMeta => const TaskConstMeta(
        debugName: "save_queue",
        argNames: ["dbPath", "snapshot"],
      );

  @override
  Stream<ScanProgress> crateApiCatalogScanLibrary(
      {required String dbPath, required List<String> roots}) {
    final sink = RustStreamSink<ScanProgress>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_list_String(roots, serializer);
        sse_encode_StreamSink_scan_progress_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogScanLibraryConstMeta,
      argValues: [dbPath, roots, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCatalogScanLibraryConstMeta => const TaskConstMeta(
        debugName: "scan_library",
        argNames: ["dbPath", "roots", "sink"],
      );

  @override
  Future<void> crateApiSettingsSetSetting(
      {required String dbPath, required String key, required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(key, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSettingsSetSettingConstMeta,
      argValues: [dbPath, key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsSetSettingConstMeta => const TaskConstMeta(
        debugName: "set_setting",
        argNames: ["dbPath", "key", "value"],
      );

  @override
  Future<String?> crateApiCatalogTrackPath(
      {required String dbPath, required PlatformInt64 trackId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_i_64(trackId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogTrackPathConstMeta,
      argValues: [dbPath, trackId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogTrackPathConstMeta => const TaskConstMeta(
        debugName: "track_path",
        argNames: ["dbPath", "trackId"],
      );

  @override
  Future<List<String>> crateApiCatalogTrackPathsForArtist(
      {required String dbPath, required String albumArtistMbid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(albumArtistMbid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogTrackPathsForArtistConstMeta,
      argValues: [dbPath, albumArtistMbid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogTrackPathsForArtistConstMeta =>
      const TaskConstMeta(
        debugName: "track_paths_for_artist",
        argNames: ["dbPath", "albumArtistMbid"],
      );

  @override
  Future<List<QueueTrack>> crateApiCatalogTracksForPaths(
      {required String dbPath, required List<String> paths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_list_String(paths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_queue_track,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCatalogTracksForPathsConstMeta,
      argValues: [dbPath, paths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCatalogTracksForPathsConstMeta =>
      const TaskConstMeta(
        debugName: "tracks_for_paths",
        argNames: ["dbPath", "paths"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<EnrichProgress> dco_decode_StreamSink_enrich_progress_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ScanProgress> dco_decode_StreamSink_scan_progress_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Album dco_decode_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Album(
      releaseMbid: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      albumArtist: dco_decode_String(arr[2]),
      originalYear: dco_decode_opt_String(arr[3]),
      reissueYear: dco_decode_opt_String(arr[4]),
      titleTranslit: dco_decode_opt_String(arr[5]),
      titleTranslate: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  Artist dco_decode_artist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Artist(
      mbid: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      sortName: dco_decode_String(arr[2]),
      transliteration: dco_decode_opt_String(arr[3]),
      nameOriginal: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  QueueSnapshot dco_decode_box_autoadd_queue_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_queue_snapshot(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  EnrichProgress dco_decode_enrich_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EnrichProgress(
      entitiesDone: dco_decode_u_64(arr[0]),
      entitiesTotal: dco_decode_u_64(arr[1]),
      current: dco_decode_String(arr[2]),
      done: dco_decode_bool(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Album> dco_decode_list_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_album).toList();
  }

  @protected
  List<Artist> dco_decode_list_artist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_artist).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<QueueTrack> dco_decode_list_queue_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_queue_track).toList();
  }

  @protected
  List<Track> dco_decode_list_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  QueueSnapshot? dco_decode_opt_box_autoadd_queue_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_queue_snapshot(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  QueueSnapshot dco_decode_queue_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return QueueSnapshot(
      paths: dco_decode_list_String(arr[0]),
      currentIndex: dco_decode_u_32(arr[1]),
      positionMs: dco_decode_u_64(arr[2]),
      shuffle: dco_decode_bool(arr[3]),
    );
  }

  @protected
  QueueTrack dco_decode_queue_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return QueueTrack(
      path: dco_decode_String(arr[0]),
      trackId: dco_decode_opt_box_autoadd_i_64(arr[1]),
      title: dco_decode_String(arr[2]),
      artist: dco_decode_opt_String(arr[3]),
      album: dco_decode_String(arr[4]),
      lengthMs: dco_decode_opt_box_autoadd_u_64(arr[5]),
      titleTranslit: dco_decode_opt_String(arr[6]),
      titleTranslate: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ScanProgress(
      filesSeen: dco_decode_u_64(arr[0]),
      filesChanged: dco_decode_u_64(arr[1]),
      current: dco_decode_String(arr[2]),
      done: dco_decode_bool(arr[3]),
    );
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Track(
      id: dco_decode_i_64(arr[0]),
      disc: dco_decode_u_32(arr[1]),
      position: dco_decode_u_32(arr[2]),
      title: dco_decode_String(arr[3]),
      artist: dco_decode_opt_String(arr[4]),
      lengthMs: dco_decode_opt_box_autoadd_u_64(arr[5]),
      lastPlayed: dco_decode_opt_box_autoadd_i_64(arr[6]),
      addedAt: dco_decode_i_64(arr[7]),
      titleTranslit: dco_decode_opt_String(arr[8]),
      titleTranslate: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  TrackTags dco_decode_track_tags(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 21)
      throw Exception('unexpected arr length: expect 21 but see ${arr.length}');
    return TrackTags(
      title: dco_decode_opt_String(arr[0]),
      artist: dco_decode_opt_String(arr[1]),
      album: dco_decode_opt_String(arr[2]),
      albumArtist: dco_decode_opt_String(arr[3]),
      trackNo: dco_decode_opt_box_autoadd_u_32(arr[4]),
      trackTotal: dco_decode_opt_box_autoadd_u_32(arr[5]),
      discNo: dco_decode_opt_box_autoadd_u_32(arr[6]),
      discTotal: dco_decode_opt_box_autoadd_u_32(arr[7]),
      lengthMs: dco_decode_u_64(arr[8]),
      recordingMbid: dco_decode_opt_String(arr[9]),
      releaseMbid: dco_decode_opt_String(arr[10]),
      releaseGroupMbid: dco_decode_opt_String(arr[11]),
      artistMbid: dco_decode_opt_String(arr[12]),
      albumArtistMbid: dco_decode_opt_String(arr[13]),
      releaseTrackMbid: dco_decode_opt_String(arr[14]),
      originalDate: dco_decode_opt_String(arr[15]),
      reissueDate: dco_decode_opt_String(arr[16]),
      hasCover: dco_decode_bool(arr[17]),
      artistSort: dco_decode_opt_String(arr[18]),
      albumArtistSort: dco_decode_opt_String(arr[19]),
      codec: dco_decode_opt_String(arr[20]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<EnrichProgress> sse_decode_StreamSink_enrich_progress_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ScanProgress> sse_decode_StreamSink_scan_progress_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Album sse_decode_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_releaseMbid = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_albumArtist = sse_decode_String(deserializer);
    var var_originalYear = sse_decode_opt_String(deserializer);
    var var_reissueYear = sse_decode_opt_String(deserializer);
    var var_titleTranslit = sse_decode_opt_String(deserializer);
    var var_titleTranslate = sse_decode_opt_String(deserializer);
    return Album(
        releaseMbid: var_releaseMbid,
        title: var_title,
        albumArtist: var_albumArtist,
        originalYear: var_originalYear,
        reissueYear: var_reissueYear,
        titleTranslit: var_titleTranslit,
        titleTranslate: var_titleTranslate);
  }

  @protected
  Artist sse_decode_artist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mbid = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_sortName = sse_decode_String(deserializer);
    var var_transliteration = sse_decode_opt_String(deserializer);
    var var_nameOriginal = sse_decode_opt_String(deserializer);
    return Artist(
        mbid: var_mbid,
        name: var_name,
        sortName: var_sortName,
        transliteration: var_transliteration,
        nameOriginal: var_nameOriginal);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  QueueSnapshot sse_decode_box_autoadd_queue_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_queue_snapshot(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  EnrichProgress sse_decode_enrich_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entitiesDone = sse_decode_u_64(deserializer);
    var var_entitiesTotal = sse_decode_u_64(deserializer);
    var var_current = sse_decode_String(deserializer);
    var var_done = sse_decode_bool(deserializer);
    return EnrichProgress(
        entitiesDone: var_entitiesDone,
        entitiesTotal: var_entitiesTotal,
        current: var_current,
        done: var_done);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Album> sse_decode_list_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Album>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_album(deserializer));
    }
    return ans_;
  }

  @protected
  List<Artist> sse_decode_list_artist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Artist>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_artist(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<QueueTrack> sse_decode_list_queue_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <QueueTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_queue_track(deserializer));
    }
    return ans_;
  }

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Track>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QueueSnapshot? sse_decode_opt_box_autoadd_queue_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_queue_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QueueSnapshot sse_decode_queue_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_paths = sse_decode_list_String(deserializer);
    var var_currentIndex = sse_decode_u_32(deserializer);
    var var_positionMs = sse_decode_u_64(deserializer);
    var var_shuffle = sse_decode_bool(deserializer);
    return QueueSnapshot(
        paths: var_paths,
        currentIndex: var_currentIndex,
        positionMs: var_positionMs,
        shuffle: var_shuffle);
  }

  @protected
  QueueTrack sse_decode_queue_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_trackId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_lengthMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_titleTranslit = sse_decode_opt_String(deserializer);
    var var_titleTranslate = sse_decode_opt_String(deserializer);
    return QueueTrack(
        path: var_path,
        trackId: var_trackId,
        title: var_title,
        artist: var_artist,
        album: var_album,
        lengthMs: var_lengthMs,
        titleTranslit: var_titleTranslit,
        titleTranslate: var_titleTranslate);
  }

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filesSeen = sse_decode_u_64(deserializer);
    var var_filesChanged = sse_decode_u_64(deserializer);
    var var_current = sse_decode_String(deserializer);
    var var_done = sse_decode_bool(deserializer);
    return ScanProgress(
        filesSeen: var_filesSeen,
        filesChanged: var_filesChanged,
        current: var_current,
        done: var_done);
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_disc = sse_decode_u_32(deserializer);
    var var_position = sse_decode_u_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_lengthMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_lastPlayed = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_addedAt = sse_decode_i_64(deserializer);
    var var_titleTranslit = sse_decode_opt_String(deserializer);
    var var_titleTranslate = sse_decode_opt_String(deserializer);
    return Track(
        id: var_id,
        disc: var_disc,
        position: var_position,
        title: var_title,
        artist: var_artist,
        lengthMs: var_lengthMs,
        lastPlayed: var_lastPlayed,
        addedAt: var_addedAt,
        titleTranslit: var_titleTranslit,
        titleTranslate: var_titleTranslate);
  }

  @protected
  TrackTags sse_decode_track_tags(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_albumArtist = sse_decode_opt_String(deserializer);
    var var_trackNo = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_trackTotal = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_discNo = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_discTotal = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lengthMs = sse_decode_u_64(deserializer);
    var var_recordingMbid = sse_decode_opt_String(deserializer);
    var var_releaseMbid = sse_decode_opt_String(deserializer);
    var var_releaseGroupMbid = sse_decode_opt_String(deserializer);
    var var_artistMbid = sse_decode_opt_String(deserializer);
    var var_albumArtistMbid = sse_decode_opt_String(deserializer);
    var var_releaseTrackMbid = sse_decode_opt_String(deserializer);
    var var_originalDate = sse_decode_opt_String(deserializer);
    var var_reissueDate = sse_decode_opt_String(deserializer);
    var var_hasCover = sse_decode_bool(deserializer);
    var var_artistSort = sse_decode_opt_String(deserializer);
    var var_albumArtistSort = sse_decode_opt_String(deserializer);
    var var_codec = sse_decode_opt_String(deserializer);
    return TrackTags(
        title: var_title,
        artist: var_artist,
        album: var_album,
        albumArtist: var_albumArtist,
        trackNo: var_trackNo,
        trackTotal: var_trackTotal,
        discNo: var_discNo,
        discTotal: var_discTotal,
        lengthMs: var_lengthMs,
        recordingMbid: var_recordingMbid,
        releaseMbid: var_releaseMbid,
        releaseGroupMbid: var_releaseGroupMbid,
        artistMbid: var_artistMbid,
        albumArtistMbid: var_albumArtistMbid,
        releaseTrackMbid: var_releaseTrackMbid,
        originalDate: var_originalDate,
        reissueDate: var_reissueDate,
        hasCover: var_hasCover,
        artistSort: var_artistSort,
        albumArtistSort: var_albumArtistSort,
        codec: var_codec);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_enrich_progress_Sse(
      RustStreamSink<EnrichProgress> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_enrich_progress,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_scan_progress_Sse(
      RustStreamSink<ScanProgress> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_scan_progress,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_album(Album self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.releaseMbid, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.albumArtist, serializer);
    sse_encode_opt_String(self.originalYear, serializer);
    sse_encode_opt_String(self.reissueYear, serializer);
    sse_encode_opt_String(self.titleTranslit, serializer);
    sse_encode_opt_String(self.titleTranslate, serializer);
  }

  @protected
  void sse_encode_artist(Artist self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mbid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.sortName, serializer);
    sse_encode_opt_String(self.transliteration, serializer);
    sse_encode_opt_String(self.nameOriginal, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_queue_snapshot(
      QueueSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_queue_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_enrich_progress(
      EnrichProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.entitiesDone, serializer);
    sse_encode_u_64(self.entitiesTotal, serializer);
    sse_encode_String(self.current, serializer);
    sse_encode_bool(self.done, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_album(List<Album> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_album(item, serializer);
    }
  }

  @protected
  void sse_encode_list_artist(List<Artist> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_artist(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_queue_track(
      List<QueueTrack> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_queue_track(item, serializer);
    }
  }

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_queue_snapshot(
      QueueSnapshot? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_queue_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_queue_snapshot(QueueSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.paths, serializer);
    sse_encode_u_32(self.currentIndex, serializer);
    sse_encode_u_64(self.positionMs, serializer);
    sse_encode_bool(self.shuffle, serializer);
  }

  @protected
  void sse_encode_queue_track(QueueTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_opt_box_autoadd_i_64(self.trackId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lengthMs, serializer);
    sse_encode_opt_String(self.titleTranslit, serializer);
    sse_encode_opt_String(self.titleTranslate, serializer);
  }

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.filesSeen, serializer);
    sse_encode_u_64(self.filesChanged, serializer);
    sse_encode_String(self.current, serializer);
    sse_encode_bool(self.done, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_u_32(self.disc, serializer);
    sse_encode_u_32(self.position, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lengthMs, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastPlayed, serializer);
    sse_encode_i_64(self.addedAt, serializer);
    sse_encode_opt_String(self.titleTranslit, serializer);
    sse_encode_opt_String(self.titleTranslate, serializer);
  }

  @protected
  void sse_encode_track_tags(TrackTags self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.albumArtist, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackNo, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackTotal, serializer);
    sse_encode_opt_box_autoadd_u_32(self.discNo, serializer);
    sse_encode_opt_box_autoadd_u_32(self.discTotal, serializer);
    sse_encode_u_64(self.lengthMs, serializer);
    sse_encode_opt_String(self.recordingMbid, serializer);
    sse_encode_opt_String(self.releaseMbid, serializer);
    sse_encode_opt_String(self.releaseGroupMbid, serializer);
    sse_encode_opt_String(self.artistMbid, serializer);
    sse_encode_opt_String(self.albumArtistMbid, serializer);
    sse_encode_opt_String(self.releaseTrackMbid, serializer);
    sse_encode_opt_String(self.originalDate, serializer);
    sse_encode_opt_String(self.reissueDate, serializer);
    sse_encode_bool(self.hasCover, serializer);
    sse_encode_opt_String(self.artistSort, serializer);
    sse_encode_opt_String(self.albumArtistSort, serializer);
    sse_encode_opt_String(self.codec, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
