// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/catalog.dart';
import 'api/cover.dart';
import 'api/enrich.dart';
import 'api/queue.dart';
import 'api/settings.dart';
import 'api/simple.dart';
import 'api/tags.dart';
import 'catalog/scan.dart';
import 'catalog/schema.dart';
import 'dart:async';
import 'dart:convert';
import 'db.dart';
import 'enrich/progress.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'tags.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<EnrichProgress> dco_decode_StreamSink_enrich_progress_Sse(
      dynamic raw);

  @protected
  RustStreamSink<ScanProgress> dco_decode_StreamSink_scan_progress_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Album dco_decode_album(dynamic raw);

  @protected
  Artist dco_decode_artist(dynamic raw);

  @protected
  ArtistReading dco_decode_artist_reading(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  QueueSnapshot dco_decode_box_autoadd_queue_snapshot(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  EnrichProgress dco_decode_enrich_progress(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Album> dco_decode_list_album(dynamic raw);

  @protected
  List<Artist> dco_decode_list_artist(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QueueTrack> dco_decode_list_queue_track(dynamic raw);

  @protected
  List<SearchTrack> dco_decode_list_search_track(dynamic raw);

  @protected
  List<Track> dco_decode_list_track(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  QueueSnapshot? dco_decode_opt_box_autoadd_queue_snapshot(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  QueueSnapshot dco_decode_queue_snapshot(dynamic raw);

  @protected
  QueueTrack dco_decode_queue_track(dynamic raw);

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw);

  @protected
  SearchResults dco_decode_search_results(dynamic raw);

  @protected
  SearchTrack dco_decode_search_track(dynamic raw);

  @protected
  TitleOverride dco_decode_title_override(dynamic raw);

  @protected
  Track dco_decode_track(dynamic raw);

  @protected
  TrackTags dco_decode_track_tags(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<EnrichProgress> sse_decode_StreamSink_enrich_progress_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<ScanProgress> sse_decode_StreamSink_scan_progress_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Album sse_decode_album(SseDeserializer deserializer);

  @protected
  Artist sse_decode_artist(SseDeserializer deserializer);

  @protected
  ArtistReading sse_decode_artist_reading(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  QueueSnapshot sse_decode_box_autoadd_queue_snapshot(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  EnrichProgress sse_decode_enrich_progress(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Album> sse_decode_list_album(SseDeserializer deserializer);

  @protected
  List<Artist> sse_decode_list_artist(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QueueTrack> sse_decode_list_queue_track(SseDeserializer deserializer);

  @protected
  List<SearchTrack> sse_decode_list_search_track(SseDeserializer deserializer);

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  QueueSnapshot? sse_decode_opt_box_autoadd_queue_snapshot(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  QueueSnapshot sse_decode_queue_snapshot(SseDeserializer deserializer);

  @protected
  QueueTrack sse_decode_queue_track(SseDeserializer deserializer);

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer);

  @protected
  SearchResults sse_decode_search_results(SseDeserializer deserializer);

  @protected
  SearchTrack sse_decode_search_track(SseDeserializer deserializer);

  @protected
  TitleOverride sse_decode_title_override(SseDeserializer deserializer);

  @protected
  Track sse_decode_track(SseDeserializer deserializer);

  @protected
  TrackTags sse_decode_track_tags(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_enrich_progress_Sse(
      RustStreamSink<EnrichProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_scan_progress_Sse(
      RustStreamSink<ScanProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album(Album self, SseSerializer serializer);

  @protected
  void sse_encode_artist(Artist self, SseSerializer serializer);

  @protected
  void sse_encode_artist_reading(ArtistReading self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_queue_snapshot(
      QueueSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_enrich_progress(
      EnrichProgress self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album(List<Album> self, SseSerializer serializer);

  @protected
  void sse_encode_list_artist(List<Artist> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_queue_track(
      List<QueueTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_search_track(
      List<SearchTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_queue_snapshot(
      QueueSnapshot? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_queue_snapshot(QueueSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_queue_track(QueueTrack self, SseSerializer serializer);

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer);

  @protected
  void sse_encode_search_results(SearchResults self, SseSerializer serializer);

  @protected
  void sse_encode_search_track(SearchTrack self, SseSerializer serializer);

  @protected
  void sse_encode_title_override(TitleOverride self, SseSerializer serializer);

  @protected
  void sse_encode_track(Track self, SseSerializer serializer);

  @protected
  void sse_encode_track_tags(TrackTags self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
