// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TrackTags {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final int? trackNo;
  final int? trackTotal;
  final int? discNo;
  final int? discTotal;
  final BigInt lengthMs;
  final String? recordingMbid;
  final String? releaseMbid;
  final String? releaseGroupMbid;
  final String? artistMbid;
  final String? albumArtistMbid;
  final String? releaseTrackMbid;
  final String? originalDate;
  final String? reissueDate;
  final bool hasCover;
  final String? artistSort;
  final String? albumArtistSort;
  final String? codec;

  const TrackTags({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.trackNo,
    this.trackTotal,
    this.discNo,
    this.discTotal,
    required this.lengthMs,
    this.recordingMbid,
    this.releaseMbid,
    this.releaseGroupMbid,
    this.artistMbid,
    this.albumArtistMbid,
    this.releaseTrackMbid,
    this.originalDate,
    this.reissueDate,
    required this.hasCover,
    this.artistSort,
    this.albumArtistSort,
    this.codec,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      trackNo.hashCode ^
      trackTotal.hashCode ^
      discNo.hashCode ^
      discTotal.hashCode ^
      lengthMs.hashCode ^
      recordingMbid.hashCode ^
      releaseMbid.hashCode ^
      releaseGroupMbid.hashCode ^
      artistMbid.hashCode ^
      albumArtistMbid.hashCode ^
      releaseTrackMbid.hashCode ^
      originalDate.hashCode ^
      reissueDate.hashCode ^
      hasCover.hashCode ^
      artistSort.hashCode ^
      albumArtistSort.hashCode ^
      codec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackTags &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          trackNo == other.trackNo &&
          trackTotal == other.trackTotal &&
          discNo == other.discNo &&
          discTotal == other.discTotal &&
          lengthMs == other.lengthMs &&
          recordingMbid == other.recordingMbid &&
          releaseMbid == other.releaseMbid &&
          releaseGroupMbid == other.releaseGroupMbid &&
          artistMbid == other.artistMbid &&
          albumArtistMbid == other.albumArtistMbid &&
          releaseTrackMbid == other.releaseTrackMbid &&
          originalDate == other.originalDate &&
          reissueDate == other.reissueDate &&
          hasCover == other.hasCover &&
          artistSort == other.artistSort &&
          albumArtistSort == other.albumArtistSort &&
          codec == other.codec;
}
