// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Streamed enrichment progress, mirroring `catalog::scan::ScanProgress`.
class EnrichProgress {
  /// Unique album-artists + releases processed so far.
  final BigInt entitiesDone;

  /// Total entities to process this run (artists + releases).
  final BigInt entitiesTotal;

  /// Human-readable label of the current entity (artist/album name).
  final String current;
  final bool done;

  const EnrichProgress({
    required this.entitiesDone,
    required this.entitiesTotal,
    required this.current,
    required this.done,
  });

  @override
  int get hashCode =>
      entitiesDone.hashCode ^
      entitiesTotal.hashCode ^
      current.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrichProgress &&
          runtimeType == other.runtimeType &&
          entitiesDone == other.entitiesDone &&
          entitiesTotal == other.entitiesTotal &&
          current == other.current &&
          done == other.done;
}
