// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A playlist with its track count (for the list view).
class Playlist {
  final PlatformInt64 id;
  final String name;
  final PlatformInt64 count;

  const Playlist({
    required this.id,
    required this.name,
    required this.count,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Playlist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          count == other.count;
}
