// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Album {
  final String releaseMbid;
  final String title;
  final String albumArtist;
  final String? originalYear;
  final String? reissueYear;
  final String? titleTranslit;
  final String? titleTranslate;

  /// earliest file added_at across the album's tracks, unix seconds; 0 if unknown
  final PlatformInt64 addedAt;

  const Album({
    required this.releaseMbid,
    required this.title,
    required this.albumArtist,
    this.originalYear,
    this.reissueYear,
    this.titleTranslit,
    this.titleTranslate,
    required this.addedAt,
  });

  @override
  int get hashCode =>
      releaseMbid.hashCode ^
      title.hashCode ^
      albumArtist.hashCode ^
      originalYear.hashCode ^
      reissueYear.hashCode ^
      titleTranslit.hashCode ^
      titleTranslate.hashCode ^
      addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Album &&
          runtimeType == other.runtimeType &&
          releaseMbid == other.releaseMbid &&
          title == other.title &&
          albumArtist == other.albumArtist &&
          originalYear == other.originalYear &&
          reissueYear == other.reissueYear &&
          titleTranslit == other.titleTranslit &&
          titleTranslate == other.titleTranslate &&
          addedAt == other.addedAt;
}

class Artist {
  final String mbid;
  final String name;
  final String sortName;
  final String? transliteration;

  /// Original-script name from MusicBrainz (e.g. 椎名林檎) — present once
  /// enriched; the tag-derived `name` may itself be a romanization.
  final String? nameOriginal;

  const Artist({
    required this.mbid,
    required this.name,
    required this.sortName,
    this.transliteration,
    this.nameOriginal,
  });

  @override
  int get hashCode =>
      mbid.hashCode ^
      name.hashCode ^
      sortName.hashCode ^
      transliteration.hashCode ^
      nameOriginal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Artist &&
          runtimeType == other.runtimeType &&
          mbid == other.mbid &&
          name == other.name &&
          sortName == other.sortName &&
          transliteration == other.transliteration &&
          nameOriginal == other.nameOriginal;
}

/// A queue entry paired with its catalog metadata, keyed by file path — used to
/// rebuild the now-playing items for a restored session. `track_id` is None when
/// the path is no longer in the catalog (then `title` falls back to the filename).
class QueueTrack {
  final String path;
  final PlatformInt64? trackId;
  final String title;
  final String? artist;
  final String album;
  final BigInt? lengthMs;
  final String? titleTranslit;
  final String? titleTranslate;

  const QueueTrack({
    required this.path,
    this.trackId,
    required this.title,
    this.artist,
    required this.album,
    this.lengthMs,
    this.titleTranslit,
    this.titleTranslate,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      trackId.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      lengthMs.hashCode ^
      titleTranslit.hashCode ^
      titleTranslate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueueTrack &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          trackId == other.trackId &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          lengthMs == other.lengthMs &&
          titleTranslit == other.titleTranslit &&
          titleTranslate == other.titleTranslate;
}

class Track {
  final PlatformInt64 id;
  final int disc;
  final int position;
  final String title;
  final String? artist;
  final BigInt? lengthMs;
  final PlatformInt64? lastPlayed;
  final PlatformInt64 addedAt;
  final String? titleTranslit;
  final String? titleTranslate;

  const Track({
    required this.id,
    required this.disc,
    required this.position,
    required this.title,
    this.artist,
    this.lengthMs,
    this.lastPlayed,
    required this.addedAt,
    this.titleTranslit,
    this.titleTranslate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      disc.hashCode ^
      position.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      lengthMs.hashCode ^
      lastPlayed.hashCode ^
      addedAt.hashCode ^
      titleTranslit.hashCode ^
      titleTranslate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          disc == other.disc &&
          position == other.position &&
          title == other.title &&
          artist == other.artist &&
          lengthMs == other.lengthMs &&
          lastPlayed == other.lastPlayed &&
          addedAt == other.addedAt &&
          titleTranslit == other.titleTranslit &&
          titleTranslate == other.titleTranslate;
}
