// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Album {
  final String releaseMbid;
  final String title;
  final String albumArtist;
  final String? originalYear;
  final String? reissueYear;

  const Album({
    required this.releaseMbid,
    required this.title,
    required this.albumArtist,
    this.originalYear,
    this.reissueYear,
  });

  @override
  int get hashCode =>
      releaseMbid.hashCode ^
      title.hashCode ^
      albumArtist.hashCode ^
      originalYear.hashCode ^
      reissueYear.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Album &&
          runtimeType == other.runtimeType &&
          releaseMbid == other.releaseMbid &&
          title == other.title &&
          albumArtist == other.albumArtist &&
          originalYear == other.originalYear &&
          reissueYear == other.reissueYear;
}

class Artist {
  final String mbid;
  final String name;
  final String sortName;

  const Artist({
    required this.mbid,
    required this.name,
    required this.sortName,
  });

  @override
  int get hashCode => mbid.hashCode ^ name.hashCode ^ sortName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Artist &&
          runtimeType == other.runtimeType &&
          mbid == other.mbid &&
          name == other.name &&
          sortName == other.sortName;
}

class Track {
  final PlatformInt64 id;
  final int disc;
  final int position;
  final String title;
  final String? artist;
  final BigInt? lengthMs;
  final PlatformInt64? lastPlayed;
  final PlatformInt64 addedAt;

  const Track({
    required this.id,
    required this.disc,
    required this.position,
    required this.title,
    this.artist,
    this.lengthMs,
    this.lastPlayed,
    required this.addedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      disc.hashCode ^
      position.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      lengthMs.hashCode ^
      lastPlayed.hashCode ^
      addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          disc == other.disc &&
          position == other.position &&
          title == other.title &&
          artist == other.artist &&
          lengthMs == other.lengthMs &&
          lastPlayed == other.lastPlayed &&
          addedAt == other.addedAt;
}
