// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Append one timestamped line to the shared activity/error log
/// (`import-log.log`, next to the DB), so Dart-side errors join the Rust-side
/// scan/enrich decisions in one log. `DecisionLog` swallows its own IO errors,
/// so this can never fail a caller.
Future<void> logActivity(
        {required String dbPath,
        required String category,
        required String detail}) =>
    RustLib.instance.api.crateApiActivityLogActivity(
        dbPath: dbPath, category: category, detail: detail);
