// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../catalog/scan.dart';
import '../catalog/schema.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ScanProgress> scanLibrary(
        {required String dbPath, required List<String> roots}) =>
    RustLib.instance.api
        .crateApiCatalogScanLibrary(dbPath: dbPath, roots: roots);

Future<void> rereadTrackTags(
        {required String dbPath, required PlatformInt64 trackId}) =>
    RustLib.instance.api
        .crateApiCatalogRereadTrackTags(dbPath: dbPath, trackId: trackId);

Future<void> rereadAlbumTags(
        {required String dbPath, required String releaseMbid}) =>
    RustLib.instance.api.crateApiCatalogRereadAlbumTags(
        dbPath: dbPath, releaseMbid: releaseMbid);

Future<List<Artist>> listArtists(
        {required String dbPath, String? after, required int limit}) =>
    RustLib.instance.api
        .crateApiCatalogListArtists(dbPath: dbPath, after: after, limit: limit);

Future<ArtistReading> artistReading(
        {required String dbPath, required String mbid}) =>
    RustLib.instance.api
        .crateApiCatalogArtistReading(dbPath: dbPath, mbid: mbid);

Future<void> setArtistReadingOverride(
        {required String dbPath,
        required String mbid,
        String? reading,
        String? sort}) =>
    RustLib.instance.api.crateApiCatalogSetArtistReadingOverride(
        dbPath: dbPath, mbid: mbid, reading: reading, sort: sort);

Future<List<Album>> listAlbums(
        {required String dbPath, required String albumArtistMbid}) =>
    RustLib.instance.api.crateApiCatalogListAlbums(
        dbPath: dbPath, albumArtistMbid: albumArtistMbid);

Future<List<Track>> listTracks(
        {required String dbPath, required String releaseMbid}) =>
    RustLib.instance.api
        .crateApiCatalogListTracks(dbPath: dbPath, releaseMbid: releaseMbid);

Future<List<String>> albumFilePaths(
        {required String dbPath, required String releaseMbid}) =>
    RustLib.instance.api.crateApiCatalogAlbumFilePaths(
        dbPath: dbPath, releaseMbid: releaseMbid);

Future<List<QueueTrack>> tracksForPaths(
        {required String dbPath, required List<String> paths}) =>
    RustLib.instance.api
        .crateApiCatalogTracksForPaths(dbPath: dbPath, paths: paths);

Future<String?> trackPath(
        {required String dbPath, required PlatformInt64 trackId}) =>
    RustLib.instance.api
        .crateApiCatalogTrackPath(dbPath: dbPath, trackId: trackId);

Future<List<String>> trackPathsForArtist(
        {required String dbPath, required String albumArtistMbid}) =>
    RustLib.instance.api.crateApiCatalogTrackPathsForArtist(
        dbPath: dbPath, albumArtistMbid: albumArtistMbid);

Future<List<String>> trackPathsForLibrary({required String dbPath}) =>
    RustLib.instance.api.crateApiCatalogTrackPathsForLibrary(dbPath: dbPath);

Future<void> recordPlay(
        {required String dbPath,
        required PlatformInt64 trackId,
        required PlatformInt64 playedAt}) =>
    RustLib.instance.api.crateApiCatalogRecordPlay(
        dbPath: dbPath, trackId: trackId, playedAt: playedAt);

Future<void> addRoot({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiCatalogAddRoot(dbPath: dbPath, path: path);

Future<void> removeRoot({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiCatalogRemoveRoot(dbPath: dbPath, path: path);

Future<void> removeTrack(
        {required String dbPath, required PlatformInt64 trackId}) =>
    RustLib.instance.api
        .crateApiCatalogRemoveTrack(dbPath: dbPath, trackId: trackId);

Future<void> removeAlbum(
        {required String dbPath, required String releaseMbid}) =>
    RustLib.instance.api
        .crateApiCatalogRemoveAlbum(dbPath: dbPath, releaseMbid: releaseMbid);

Future<List<String>> listRoots({required String dbPath}) =>
    RustLib.instance.api.crateApiCatalogListRoots(dbPath: dbPath);
