// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cover_runtime`

/// Resolve the cover for an album (release): embedded art from a representative
/// file -> Cover Art Archive -> None. Returns a cached image path or None.
Future<String?> coverForRelease(
        {required String dbPath,
        required String releaseMbid,
        required String cacheDir}) =>
    RustLib.instance.api.crateApiCoverCoverForRelease(
        dbPath: dbPath, releaseMbid: releaseMbid, cacheDir: cacheDir);

/// Resolve the cover for the album a given file belongs to (the now-playing
/// track). Falls back to the file's own embedded art if the path is not in the
/// catalog.
Future<String?> coverForPath(
        {required String dbPath,
        required String filePath,
        required String cacheDir}) =>
    RustLib.instance.api.crateApiCoverCoverForPath(
        dbPath: dbPath, filePath: filePath, cacheDir: cacheDir);
