// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../enrich/progress.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `enrich_runtime`

/// Stream enrichment progress to Dart. `force=false` is the resumable auto path
/// (skips already-enriched files + cached entities); `force=true` re-runs the
/// logic over everything, still reading entity JSON from the cache.
///
/// SYNC fn (like `scan_library`): dispatched on frb's worker-thread path. The
/// async enrichment core is driven by a private current-thread tokio runtime
/// via `block_on` — NOT frb's async executor, which would reject the non-`Send`
/// `Connection`/`RefCell`/`?Send` types this design holds across `.await`.
Stream<EnrichProgress> enrichLibrary(
        {required String dbPath, required bool force}) =>
    RustLib.instance.api
        .crateApiEnrichEnrichLibrary(dbPath: dbPath, force: force);

/// Empty the MusicBrainz response cache so the next enrich refetches from the
/// network (spec §4: manual refresh only).
Future<void> clearMbCache({required String dbPath}) =>
    RustLib.instance.api.crateApiEnrichClearMbCache(dbPath: dbPath);
