// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../catalog/playlists.dart';
import '../catalog/schema.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<PlatformInt64> createPlaylist(
        {required String dbPath, required String name}) =>
    RustLib.instance.api
        .crateApiPlaylistsCreatePlaylist(dbPath: dbPath, name: name);

Future<void> renamePlaylist(
        {required String dbPath,
        required PlatformInt64 id,
        required String name}) =>
    RustLib.instance.api
        .crateApiPlaylistsRenamePlaylist(dbPath: dbPath, id: id, name: name);

Future<void> deletePlaylist(
        {required String dbPath, required PlatformInt64 id}) =>
    RustLib.instance.api
        .crateApiPlaylistsDeletePlaylist(dbPath: dbPath, id: id);

Future<void> reorderPlaylists(
        {required String dbPath, required Int64List ids}) =>
    RustLib.instance.api
        .crateApiPlaylistsReorderPlaylists(dbPath: dbPath, ids: ids);

Future<List<Playlist>> listPlaylists({required String dbPath}) =>
    RustLib.instance.api.crateApiPlaylistsListPlaylists(dbPath: dbPath);

Future<List<QueueTrack>> playlistTracks(
        {required String dbPath, required PlatformInt64 id}) =>
    RustLib.instance.api
        .crateApiPlaylistsPlaylistTracks(dbPath: dbPath, id: id);

Future<void> addToPlaylist(
        {required String dbPath,
        required PlatformInt64 id,
        required List<String> paths}) =>
    RustLib.instance.api
        .crateApiPlaylistsAddToPlaylist(dbPath: dbPath, id: id, paths: paths);

Future<void> setPlaylistItems(
        {required String dbPath,
        required PlatformInt64 id,
        required List<String> paths}) =>
    RustLib.instance.api.crateApiPlaylistsSetPlaylistItems(
        dbPath: dbPath, id: id, paths: paths);
