// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Write a phone-ready snapshot of the catalog into `dest_dir` (a folder
/// Syncthing replicates to the device). See [`crate::sync::export_snapshot`].
Future<SnapshotResult> exportSyncSnapshot(
        {required String dbPath,
        required String destDir,
        String? cacheDir,
        required List<RootMapping> mappings}) =>
    RustLib.instance.api.crateApiSyncExportSyncSnapshot(
        dbPath: dbPath,
        destDir: destDir,
        cacheDir: cacheDir,
        mappings: mappings);

/// One library root paired with where its files live on the phone.
class RootMapping {
  final String desktop;
  final String phone;

  const RootMapping({
    required this.desktop,
    required this.phone,
  });

  @override
  int get hashCode => desktop.hashCode ^ phone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RootMapping &&
          runtimeType == other.runtimeType &&
          desktop == other.desktop &&
          phone == other.phone;
}

/// What an export produced, for the confirmation the UI shows.
class SnapshotResult {
  final String dbPath;
  final PlatformInt64 files;
  final PlatformInt64 coversCopied;

  const SnapshotResult({
    required this.dbPath,
    required this.files,
    required this.coversCopied,
  });

  @override
  int get hashCode => dbPath.hashCode ^ files.hashCode ^ coversCopied.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotResult &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          files == other.files &&
          coversCopied == other.coversCopied;
}
